FROM ruby:3.3-slim

# Install essential Linux packages
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy only Gemfile and Gemfile.lock initially 
# (for better caching of Docker layers)
COPY Gemfile* ./

# Install bundle dependencies
RUN bundle install

# Copy the rest of the site files
COPY * .

# Expose port 4000, the default Jekyll port
EXPOSE 4000

# Set environment to development
ENV JEKYLL_ENV=development

# Command to run when container starts
CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0"]