version: '3.8'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile_local_dev
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload